# -*- coding: utf-8 -*-
"""productreview

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8utxc9d1S4ZadryaaPsn07iDZPrjdqF
"""

!pip install transformers torch pandas

from transformers import pipeline
import pandas as pd

sentiment = pipeline("sentiment-analysis")
reviews = """The laptop starts quick and works smoothly for daily tasks.
the screen quality is clear and good for watching videos"""
sentence = reviews.split(".")
pros = [ ]
cons = [ ]
for s in sentence:
  s = s.strip()
  if not s:
    continue
  result = sentiment(s)[0]
  if result["label"]=="POSITIVE":
    pros.append(s)
  elif result["label"]=="NEGATIVE":
    cons.append(s)

pros = pros[:2]
cons = cons[:2]

# Ensure both lists have the same length for DataFrame creation
max_len = max(len(pros), len(cons))
pros.extend([None] * (max_len - len(pros)))
cons.extend([None] * (max_len - len(cons)))

df = pd.DataFrame({"pros":pros,"cons":cons})
df