# -*- coding: utf-8 -*-
"""timetable generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q97FYr82Q5xD7p0NiYnwsUxqDHW4-_nm
"""

import pandas as pd
import random
print("TIMETABLE GENERATOR\n")
# user Inputs
subjects_input = input("Enter subjects (comma seperated): ")
days_input = input("Enter days (comma seperated): ")
periods_per_day = int(input("Enter number of periods per day: "))
#process Inputs
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]
#validation
if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
 print("Invalid input. Please try again.")
else:
     timetable = {}

     for day in days:
         timetable[day] = random.choices(subjects, k=periods_per_day)
# create DataFrame
         df = pd.DataFrame(timetable)
         df.index = [f"period {i+1}" for i in range(periods_per_day)]
         print("\nTimetable Generated Successfully\n")
         display(df)
 # Save timetable
         df.to_csv("timetable.csv")
         print("\nTimetable saved to timetable.csv")